[package]
name = "tendermint-verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# crates.io
futures-util = "0.3.25"

# ibc
ibc = { path = "../../../ibc/modules", features = [] }
ibc-proto = { path = "../../../ibc/proto" }
pallet-ibc = { path = "../../../contracts/pallet-ibc" }
# Tendermint
tendermint = { workspace = true }
tendermint-rpc   = { workspace = true }
tendermint-proto = { workspace = true }
tendermint-light-client = { workspace = true }
tendermint-light-client-verifier = { workspace = true }
ics07-tendermint = { path = "../../../light-clients/ics07-tendermint" }