# Relaychain Configuration
relaychain:
  image: parity/polkadot:v0.9.39 # the docker image to use
  chain: rococo-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_cooldown: 2
        validation_upgrade_delay: 2
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
    - --beefy
    - --enable-offchain-indexing=true
    - --pruning=archive
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      wsPort: 9944 # default ws port number is `9944 + global_node_index`
    - name: bob
    - name: charlie
    - name: dave
    - name: eve
    - name: ferdie

# Parachain Configuration
parachains:
  # Config for first parachain
  - image: parachain-node:latest
    chain: # this could be a string like `dev` or a config object
      base: dev-2000 # the chain to use
      collators: # override collators
        - alice # this imply //Alice
        - bob
        - charlie
      sudo: alice # override sudo key to //Alice
    id: 2000 # override parachain id
    parachain: true # this is parachain, not parathread
    flags: # CLI flags for this parachain nodes
      - --rpc-methods=unsafe
      - --wasmtime-instantiation-strategy=recreate-instance-copy-on-write
      - --log=ibc_transfer=trace,pallet_ibc=trace,grandpa-verifier=trace,runtime=trace
      - --force-authoring
      - --execution=wasm
      - --enable-offchain-indexing=true
      - --pruning=archive
    relaychainFlags: # CLI flags for the relaychain port
      - --execution=wasm
#    volumePath: /acala/data # The path to mount volume and base path, default to /data
    nodes: # nodes config
      - wsPort: 9188
        flags: # additional CLI flags for this node
          - --alice
        relaychainFlags: # additional CLI flags for relaychain part
          - --name=relaychain-alice
      - flags:
          - --bob
      - flags:
          - --charlie
  # Config for second parachain
  - image: parachain-node:latest
    chain: # this could be a string like `dev` or a config object
      base: dev-2001 # the chain to use
      collators: # override collators
        - alice # this imply //Alice
        - bob
        - charlie
      sudo: alice # override sudo key to //Alice
    id: 2001 # override parachain id
    parachain: true # this is parachain, not parathread
    flags: # CLI flags for this parachain nodes
      - --rpc-methods=unsafe
      - --wasmtime-instantiation-strategy=recreate-instance-copy-on-write
      - --log=ibc_transfer=trace,pallet_ibc=trace,grandpa-verifier=trace,runtime=trace
      - --force-authoring
      - --execution=wasm
      - --enable-offchain-indexing=true
      - --pruning=archive
    relaychainFlags: # CLI flags for the relaychain port
      - --execution=wasm
    nodes: # nodes config
      - wsPort: 9988
        flags: # additional CLI flags for this node
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
