[package]
name = "ibc-rpc"
description = "RPC apis for substrate ibc"
edition = "2021"
version = "0.1.0"
authors = ["David Salami <wizdave97@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
hex-literal = { version = "0.3.3" }
ibc-primitives = { path = "../primitives" }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
pallet-ibc = { path = ".." }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.45"

frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
ibc-proto = { path = "../../../ibc/proto", default-features = false }
ibc-runtime-api = { path = "../runtime-api" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false }

[dependencies.ibc]
path = "../../../ibc/modules"
default-features = false

[dependencies.ibc-derive]
path = "../../../ibc/derive"
default-features = false
