[package]
name = "simple-iavl"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/informalsystems/basecoin-rs"
authors = ["Informal Systems <hello@informal.systems>"]
description = """
    An simple in memory iavl
"""

[dependencies]
bytes = { version = "1.1.0", default-features = false }
ics23 = { version = "0.9.0", default-features = false }
sha2 = { version = "0.10.2", default-features = false }
tendermint = { version = "0.29.0", default-features = false }

[dev-dependencies]
proptest = "*"
rand = "*"
ics23 = { version = "0.9.0", features = ["host-functions"] }

[features]
default = ['std']
std = [
    "bytes/std",
    "ics23/std",
    "sha2/std",
    "tendermint/std"
]
